### ISSUE TITLE
New Demo Link

### ISSUE THREAD

**Issue by dbalders** [GhostCloak/BiosVision#12]
Hey, do you happen to have a new demo link for biosvision? The current one 404's. If not, are you still planning to support it and are there any example images for the theme? Thanks!

**Comment by BiosElement** [comment]
Oh dear, I never got a notification for this. :/ I'll get something up as soon as possible.

**Comment by BiosElement** [comment]
Hey @dbalders, it took an utterly inexcusably long time, but I did finally get a demo page up: http://ghostcloak.github.io/BiosVision/

Sorry for the totally unacceptable delay on that.
